exports.AccessiblityEvents = [
   'ACCESSIBILITY_SET_MESSAGE_GROUP_SPACING',
   'ACCESSIBILITY_SET_PREFERS_REDUCED_MOTION',
   'ACCESSIBILITY_DESATURATE_ROLES_TOGGLE',
   'ACCESSIBILITY_DARK_SIDEBAR_TOGGLE',
   'ACCESSIBILITY_SET_SATURATION',
   'ACCESSIBILITY_SET_FONT_SIZE',
   'ACCESSIBILITY_SET_ZOOM'
];

exports.VoiceEvents = [
   'AUDIO_SET_DISPLAY_SILENCE_WARNING',
   'AUDIO_SET_AUTOMATIC_GAIN_CONTROL',
   'MEDIA_ENGINE_SET_HARDWARE_H264',
   'MEDIA_ENGINE_SET_VIDEO_DEVICE',
   'AUDIO_SET_NOISE_SUPPRESSION',
   'AUDIO_SET_ECHO_CANCELLATION',
   'MEDIA_ENGINE_SET_OPEN_H264',
   'MEDIA_ENGINE_SET_AEC_DUMP',
   'AUDIO_SET_OUTPUT_VOLUME',
   'AUDIO_SET_OUTPUT_DEVICE',
   'AUDIO_SET_INPUT_DEVICE',
   'AUDIO_SET_ATTENUATION',
   'AUDIO_SET_MODE',
   'AUDIO_SET_QOS'
];

exports.NotificationEvents = [
   'NOTIFICATIONS_SET_DISABLE_UNREAD_BADGE',
   'NOTIFICATIONS_SET_PERMISSION_STATE',
   'NOTIFICATIONS_SET_DISABLED_SOUNDS',
   'NOTIFICATIONS_SET_TASKBAR_FLASH',
   'NOTIFICATIONS_SET_DESKTOP_TYPE',
   'NOTIFICATIONS_SET_TTS_TYPE'
];